from bot.keyboards import (
    BTN_ABONEMENT,
    BTN_BOOK,
    BTN_BOOK_AGAIN,
    BTN_BOOK_ONLINE,
    BTN_BOT_MENU,
    BTN_CABINET,
    BTN_CABINET_ABONEMENT,
    BTN_CABINET_HISTORY,
    BTN_CABINET_RECORDS,
    BTN_CABINET_REFRESH,
    BTN_CANCEL,
    BTN_CANCEL_RECORD,
    BTN_CHANGE_PHONE,
    BTN_CONTACT_ADMIN,
    BTN_CONTACTS,
    BTN_FAQ,
    BTN_FAVORITE_TRAINER,
    BTN_HELP,
    BTN_HOW_TO_USE,
    BTN_INFO,
    BTN_LOGIN,
    BTN_LOGOUT,
    BTN_MENU,
    BTN_NEXT_RECORD,
    BTN_PICK_TRAINER,
    BTN_SCHEDULE,
    BTN_SCHEDULE_5,
    BTN_SCHEDULE_10,
    BTN_SCHEDULE_15,
    BTN_SCHEDULE_MY_TRAINER,
    BTN_SCHEDULE_TODAY,
    BTN_SCHEDULE_TOMORROW,
)

_BUTTONS = {
    BTN_LOGIN,
    BTN_LOGOUT,
    BTN_BOOK,
    BTN_BOOK_AGAIN,
    BTN_CANCEL_RECORD,
    BTN_CABINET,
    BTN_SCHEDULE,
    BTN_ABONEMENT,
    BTN_NEXT_RECORD,
    BTN_INFO,
    BTN_CONTACTS,
    BTN_FAQ,
    BTN_BOOK_ONLINE,
    BTN_HOW_TO_USE,
    BTN_SCHEDULE_TODAY,
    BTN_SCHEDULE_TOMORROW,
    BTN_SCHEDULE_5,
    BTN_SCHEDULE_10,
    BTN_SCHEDULE_15,
    BTN_SCHEDULE_MY_TRAINER,
    BTN_FAVORITE_TRAINER,
    BTN_PICK_TRAINER,
    BTN_CHANGE_PHONE,
    BTN_HELP,
    BTN_MENU,
    BTN_BOT_MENU,
    BTN_CONTACT_ADMIN,
    BTN_CABINET_REFRESH,
    BTN_CABINET_RECORDS,
    BTN_CABINET_HISTORY,
    BTN_CABINET_ABONEMENT,
    BTN_CANCEL,
}

_TEXT_TRIGGERS = {
    "начать",
    "start",
    "привет",
    "меню",
    "войти",
    "вход",
    "выйти",
    "выход",
    "выйти из аккаунта",
    "записаться",
    "запись",
    "записаться снова",
    "повторить запись",
    "записаться онлайн",
    "онлайн запись",
    "отменить запись",
    "отмена записи",
    "ближайшая запись",
    "моя запись",
    "расписание",
    "мой тренер",
    "тренер",
    "избранный тренер",
    "любимый тренер",
    "выбрать тренера",
    "сменить тренера",
    "кабинет",
    "личный кабинет",
    "абонемент",
    "мой абонемент",
    "справка",
    "о студии",
    "контакты",
    "вопросы",
    "faq",
    "изменить номер",
    "сменить номер",
    "помощь",
    "как пользоваться",
    "администратор",
    "админ",
    "оператор",
    "меню бота",
    "к боту",
    "отмена",
    "назад",
}


def is_bot_command(text: str, text_lower: str) -> bool:
    if text in _BUTTONS:
        return True
    return text_lower in _TEXT_TRIGGERS
